# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 21a63a2963e2b5ad5c7da7a321e14495c4335adc9b403c6c09fcc6056440eedcaf66b054882e0ff95f0592c86e74dd4d51cdd3e1a694ffa7c72753ca5952efc7

test:
  secret_key_base: 251dbe76ddd2606059199a87e800490705f23953417087d1d91379c80ec13b34ec949183f55de29a84bd2ba7a7c524d7893dc88f7543ecb6bcb6d34630983d1e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
